"""Assignment observers copied from frozen solve kernels; no solver replacement."""

import sys as _probe_sys
from pathlib import Path as _ProbePath
_probe_root = _ProbePath(__file__).resolve().parents[1]
_probe_sys.path[:0] = [str(_probe_root/"probes"), str(_probe_root/"scripts"), str(_probe_root/"src")]

import warp as wp

@wp.kernel(module='unique')
def pair_trace(porder: wp.array(dtype=int), pidx: wp.array(dtype=int), pstart: wp.array(dtype=int), pcount: wp.array(dtype=int), pbi: wp.array(dtype=int), pbj: wp.array(dtype=int), ci: int, cstart: wp.array(dtype=int), ccount: wp.array(dtype=int), cbi: wp.array(dtype=int), cbj: wp.array(dtype=int), cpA: wp.array(dtype=wp.vec3), cpB: wp.array(dtype=wp.vec3), cn: wp.array(dtype=wp.vec3), jn: wp.array(dtype=float), jt1: wp.array(dtype=float), jt2: wp.array(dtype=float), xc: wp.array(dtype=wp.vec3), v: wp.array(dtype=wp.vec3), w: wp.array(dtype=wp.vec3), invIw: wp.array(dtype=wp.mat33), invM: wp.array(dtype=float), mu: float, t2d: float, trace: wp.array3d(dtype=wp.float64), seen: wp.array3d(dtype=int)):
    """The same chunk, chunk_mode='registers': the two bodies of the pair are loaded once, every contact
        of the chunk updates the local velocities, and they are stored once at the end. Expression for
        expression and in the same order as `f_gs_vel`, so this is the exact sequential Gauss-Seidel result
        of the chunk (the WY compression of the updates does not apply here: each of the <= 4 updates is
        state dependent through max(0, .) on the normal impulse and the projection onto the friction cone,
        so they are not a fixed product of rank-1 projectors)."""
    t = wp.tid()
    if t >= ccount[ci]:
        return
    p = porder[cstart[ci] + t]
    st = pstart[p]
    n = pcount[p]
    bi = pbi[p]
    bj = pbj[p]
    iMA = invM[bi]
    IA = invIw[bi]
    vA = v[bi]
    wA = w[bi]
    iMB = float(0.0)
    IB = invIw[bi]
    vB = wp.vec3(0.0, 0.0, 0.0)
    wB = wp.vec3(0.0, 0.0, 0.0)
    if bj >= 0:
        iMB = invM[bj]
        IB = invIw[bj]
        vB = v[bj]
        wB = w[bj]
    for k in range(n):
        c = pidx[st + k]
        nrm = cn[c]
        trace[t, k, 0] = wp.float64(nrm[0])
        seen[t, k, 0] = 1
        trace[t, k, 1] = wp.float64(nrm[1])
        seen[t, k, 1] = 1
        trace[t, k, 2] = wp.float64(nrm[2])
        seen[t, k, 2] = 1
        rA = cpA[c] - xc[bi]
        trace[t, k, 3] = wp.float64(rA[0])
        seen[t, k, 3] = 1
        trace[t, k, 4] = wp.float64(rA[1])
        seen[t, k, 4] = 1
        trace[t, k, 5] = wp.float64(rA[2])
        seen[t, k, 5] = 1
        va = vA + wp.cross(wA, rA)
        trace[t, k, 6] = wp.float64(va[0])
        seen[t, k, 6] = 1
        trace[t, k, 7] = wp.float64(va[1])
        seen[t, k, 7] = 1
        trace[t, k, 8] = wp.float64(va[2])
        seen[t, k, 8] = 1
        vb = wp.vec3(0.0, 0.0, 0.0)
        trace[t, k, 9] = wp.float64(vb[0])
        seen[t, k, 9] = 1
        trace[t, k, 10] = wp.float64(vb[1])
        seen[t, k, 10] = 1
        trace[t, k, 11] = wp.float64(vb[2])
        seen[t, k, 11] = 1
        rB = wp.vec3(0.0, 0.0, 0.0)
        trace[t, k, 12] = wp.float64(rB[0])
        seen[t, k, 12] = 1
        trace[t, k, 13] = wp.float64(rB[1])
        seen[t, k, 13] = 1
        trace[t, k, 14] = wp.float64(rB[2])
        seen[t, k, 14] = 1
        if bj >= 0:
            rB = cpB[c] - xc[bj]
            trace[t, k, 15] = wp.float64(rB[0])
            seen[t, k, 15] = 1
            trace[t, k, 16] = wp.float64(rB[1])
            seen[t, k, 16] = 1
            trace[t, k, 17] = wp.float64(rB[2])
            seen[t, k, 17] = 1
            vb = vB + wp.cross(wB, rB)
            trace[t, k, 18] = wp.float64(vb[0])
            seen[t, k, 18] = 1
            trace[t, k, 19] = wp.float64(vb[1])
            seen[t, k, 19] = 1
            trace[t, k, 20] = wp.float64(vb[2])
            seen[t, k, 20] = 1
        vrel = va - vb
        trace[t, k, 21] = wp.float64(vrel[0])
        seen[t, k, 21] = 1
        trace[t, k, 22] = wp.float64(vrel[1])
        seen[t, k, 22] = 1
        trace[t, k, 23] = wp.float64(vrel[2])
        seen[t, k, 23] = 1
        vn = wp.dot(vrel, nrm)
        trace[t, k, 24] = wp.float64(vn)
        seen[t, k, 24] = 1
        vt = vrel - vn * nrm
        trace[t, k, 25] = wp.float64(vt[0])
        seen[t, k, 25] = 1
        trace[t, k, 26] = wp.float64(vt[1])
        seen[t, k, 26] = 1
        trace[t, k, 27] = wp.float64(vt[2])
        seen[t, k, 27] = 1
        mt = wp.length(vt)
        trace[t, k, 28] = wp.float64(mt)
        seen[t, k, 28] = 1
        t1 = vt / mt
        trace[t, k, 29] = wp.float64(t1[0])
        seen[t, k, 29] = 1
        trace[t, k, 30] = wp.float64(t1[1])
        seen[t, k, 30] = 1
        trace[t, k, 31] = wp.float64(t1[2])
        seen[t, k, 31] = 1
        if mt <= 0.005:
            aa = wp.vec3(1.0, 0.0, 0.0)
            trace[t, k, 32] = wp.float64(aa[0])
            seen[t, k, 32] = 1
            trace[t, k, 33] = wp.float64(aa[1])
            seen[t, k, 33] = 1
            trace[t, k, 34] = wp.float64(aa[2])
            seen[t, k, 34] = 1
            if wp.abs(nrm[0]) >= 0.9:
                aa = wp.vec3(0.0, 1.0, 0.0)
                trace[t, k, 35] = wp.float64(aa[0])
                seen[t, k, 35] = 1
                trace[t, k, 36] = wp.float64(aa[1])
                seen[t, k, 36] = 1
                trace[t, k, 37] = wp.float64(aa[2])
                seen[t, k, 37] = 1
            t1 = wp.normalize(aa - wp.dot(aa, nrm) * nrm)
            trace[t, k, 38] = wp.float64(t1[0])
            seen[t, k, 38] = 1
            trace[t, k, 39] = wp.float64(t1[1])
            seen[t, k, 39] = 1
            trace[t, k, 40] = wp.float64(t1[2])
            seen[t, k, 40] = 1
        t2 = wp.cross(nrm, t1)
        trace[t, k, 41] = wp.float64(t2[0])
        seen[t, k, 41] = 1
        trace[t, k, 42] = wp.float64(t2[1])
        seen[t, k, 42] = 1
        trace[t, k, 43] = wp.float64(t2[2])
        seen[t, k, 43] = 1
        rnA = wp.cross(rA, nrm)
        trace[t, k, 44] = wp.float64(rnA[0])
        seen[t, k, 44] = 1
        trace[t, k, 45] = wp.float64(rnA[1])
        seen[t, k, 45] = 1
        trace[t, k, 46] = wp.float64(rnA[2])
        seen[t, k, 46] = 1
        meff = iMA + wp.dot(rnA, IA * rnA)
        trace[t, k, 47] = wp.float64(meff)
        seen[t, k, 47] = 1
        if bj >= 0:
            rnB = wp.cross(rB, nrm)
            trace[t, k, 48] = wp.float64(rnB[0])
            seen[t, k, 48] = 1
            trace[t, k, 49] = wp.float64(rnB[1])
            seen[t, k, 49] = 1
            trace[t, k, 50] = wp.float64(rnB[2])
            seen[t, k, 50] = 1
            meff = meff + iMB + wp.dot(rnB, IB * rnB)
            trace[t, k, 51] = wp.float64(meff)
            seen[t, k, 51] = 1
        if meff >= 1e-12:
            dj = -vn / meff
            trace[t, k, 52] = wp.float64(dj)
            seen[t, k, 52] = 1
            nw = wp.max(0.0, jn[c] + dj)
            trace[t, k, 53] = wp.float64(nw)
            seen[t, k, 53] = 1
            dj = nw - jn[c]
            trace[t, k, 54] = wp.float64(dj)
            seen[t, k, 54] = 1
            jn[c] = nw
            Jn = dj * nrm
            trace[t, k, 55] = wp.float64(Jn[0])
            seen[t, k, 55] = 1
            trace[t, k, 56] = wp.float64(Jn[1])
            seen[t, k, 56] = 1
            trace[t, k, 57] = wp.float64(Jn[2])
            seen[t, k, 57] = 1
            if iMA > 0.0:
                vA = vA + Jn * iMA
                trace[t, k, 58] = wp.float64(vA[0])
                seen[t, k, 58] = 1
                trace[t, k, 59] = wp.float64(vA[1])
                seen[t, k, 59] = 1
                trace[t, k, 60] = wp.float64(vA[2])
                seen[t, k, 60] = 1
                wA = wA + IA * wp.cross(rA, Jn)
                trace[t, k, 61] = wp.float64(wA[0])
                seen[t, k, 61] = 1
                trace[t, k, 62] = wp.float64(wA[1])
                seen[t, k, 62] = 1
                trace[t, k, 63] = wp.float64(wA[2])
                seen[t, k, 63] = 1
            if bj >= 0:
                if iMB > 0.0:
                    vB = vB - Jn * iMB
                    trace[t, k, 64] = wp.float64(vB[0])
                    seen[t, k, 64] = 1
                    trace[t, k, 65] = wp.float64(vB[1])
                    seen[t, k, 65] = 1
                    trace[t, k, 66] = wp.float64(vB[2])
                    seen[t, k, 66] = 1
                    wB = wB - IB * wp.cross(rB, Jn)
                    trace[t, k, 67] = wp.float64(wB[0])
                    seen[t, k, 67] = 1
                    trace[t, k, 68] = wp.float64(wB[1])
                    seen[t, k, 68] = 1
                    trace[t, k, 69] = wp.float64(wB[2])
                    seen[t, k, 69] = 1
            va = vA + wp.cross(wA, rA)
            trace[t, k, 70] = wp.float64(va[0])
            seen[t, k, 70] = 1
            trace[t, k, 71] = wp.float64(va[1])
            seen[t, k, 71] = 1
            trace[t, k, 72] = wp.float64(va[2])
            seen[t, k, 72] = 1
            vb = wp.vec3(0.0, 0.0, 0.0)
            trace[t, k, 73] = wp.float64(vb[0])
            seen[t, k, 73] = 1
            trace[t, k, 74] = wp.float64(vb[1])
            seen[t, k, 74] = 1
            trace[t, k, 75] = wp.float64(vb[2])
            seen[t, k, 75] = 1
            if bj >= 0:
                vb = vB + wp.cross(wB, rB)
                trace[t, k, 76] = wp.float64(vb[0])
                seen[t, k, 76] = 1
                trace[t, k, 77] = wp.float64(vb[1])
                seen[t, k, 77] = 1
                trace[t, k, 78] = wp.float64(vb[2])
                seen[t, k, 78] = 1
            vrel = va - vb
            trace[t, k, 79] = wp.float64(vrel[0])
            seen[t, k, 79] = 1
            trace[t, k, 80] = wp.float64(vrel[1])
            seen[t, k, 80] = 1
            trace[t, k, 81] = wp.float64(vrel[2])
            seen[t, k, 81] = 1
            rtA1 = wp.cross(rA, t1)
            trace[t, k, 82] = wp.float64(rtA1[0])
            seen[t, k, 82] = 1
            trace[t, k, 83] = wp.float64(rtA1[1])
            seen[t, k, 83] = 1
            trace[t, k, 84] = wp.float64(rtA1[2])
            seen[t, k, 84] = 1
            meft1 = iMA + wp.dot(rtA1, IA * rtA1)
            trace[t, k, 85] = wp.float64(meft1)
            seen[t, k, 85] = 1
            rtA2 = wp.cross(rA, t2)
            trace[t, k, 86] = wp.float64(rtA2[0])
            seen[t, k, 86] = 1
            trace[t, k, 87] = wp.float64(rtA2[1])
            seen[t, k, 87] = 1
            trace[t, k, 88] = wp.float64(rtA2[2])
            seen[t, k, 88] = 1
            meft2 = iMA + wp.dot(rtA2, IA * rtA2)
            trace[t, k, 89] = wp.float64(meft2)
            seen[t, k, 89] = 1
            if bj >= 0:
                rtB1 = wp.cross(rB, t1)
                trace[t, k, 90] = wp.float64(rtB1[0])
                seen[t, k, 90] = 1
                trace[t, k, 91] = wp.float64(rtB1[1])
                seen[t, k, 91] = 1
                trace[t, k, 92] = wp.float64(rtB1[2])
                seen[t, k, 92] = 1
                meft1 = meft1 + iMB + wp.dot(rtB1, IB * rtB1)
                trace[t, k, 93] = wp.float64(meft1)
                seen[t, k, 93] = 1
                rtB2 = wp.cross(rB, t2)
                trace[t, k, 94] = wp.float64(rtB2[0])
                seen[t, k, 94] = 1
                trace[t, k, 95] = wp.float64(rtB2[1])
                seen[t, k, 95] = 1
                trace[t, k, 96] = wp.float64(rtB2[2])
                seen[t, k, 96] = 1
                meft2 = meft2 + iMB + wp.dot(rtB2, IB * rtB2)
                trace[t, k, 97] = wp.float64(meft2)
                seen[t, k, 97] = 1
            if meft1 >= 1e-12:
                if meft2 >= 1e-12:
                    o1 = jt1[c]
                    trace[t, k, 98] = wp.float64(o1)
                    seen[t, k, 98] = 1
                    o2 = jt2[c]
                    trace[t, k, 99] = wp.float64(o2)
                    seen[t, k, 99] = 1
                    a1 = o1 - wp.dot(vrel, t1) / meft1
                    trace[t, k, 100] = wp.float64(a1)
                    seen[t, k, 100] = 1
                    a2 = o2 - wp.dot(vrel, t2) / meft2
                    trace[t, k, 101] = wp.float64(a2)
                    seen[t, k, 101] = 1
                    mag = wp.sqrt(a1 * a1 + a2 * a2)
                    trace[t, k, 102] = wp.float64(mag)
                    seen[t, k, 102] = 1
                    lim = mu * jn[c]
                    trace[t, k, 103] = wp.float64(lim)
                    seen[t, k, 103] = 1
                    if mag > lim and mag > 1e-12:
                        a1 = a1 * lim / mag
                        trace[t, k, 104] = wp.float64(a1)
                        seen[t, k, 104] = 1
                        a2 = a2 * lim / mag
                        trace[t, k, 105] = wp.float64(a2)
                        seen[t, k, 105] = 1
                    jt1[c] = a1
                    jt2[c] = a2
                    Jt = (a1 - o1) * t1 + t2d * (a2 - o2) * t2
                    trace[t, k, 106] = wp.float64(Jt[0])
                    seen[t, k, 106] = 1
                    trace[t, k, 107] = wp.float64(Jt[1])
                    seen[t, k, 107] = 1
                    trace[t, k, 108] = wp.float64(Jt[2])
                    seen[t, k, 108] = 1
                    if iMA > 0.0:
                        vA = vA + Jt * iMA
                        trace[t, k, 109] = wp.float64(vA[0])
                        seen[t, k, 109] = 1
                        trace[t, k, 110] = wp.float64(vA[1])
                        seen[t, k, 110] = 1
                        trace[t, k, 111] = wp.float64(vA[2])
                        seen[t, k, 111] = 1
                        wA = wA + IA * wp.cross(rA, Jt)
                        trace[t, k, 112] = wp.float64(wA[0])
                        seen[t, k, 112] = 1
                        trace[t, k, 113] = wp.float64(wA[1])
                        seen[t, k, 113] = 1
                        trace[t, k, 114] = wp.float64(wA[2])
                        seen[t, k, 114] = 1
                    if bj >= 0:
                        if iMB > 0.0:
                            vB = vB - Jt * iMB
                            trace[t, k, 115] = wp.float64(vB[0])
                            seen[t, k, 115] = 1
                            trace[t, k, 116] = wp.float64(vB[1])
                            seen[t, k, 116] = 1
                            trace[t, k, 117] = wp.float64(vB[2])
                            seen[t, k, 117] = 1
                            wB = wB - IB * wp.cross(rB, Jt)
                            trace[t, k, 118] = wp.float64(wB[0])
                            seen[t, k, 118] = 1
                            trace[t, k, 119] = wp.float64(wB[1])
                            seen[t, k, 119] = 1
                            trace[t, k, 120] = wp.float64(wB[2])
                            seen[t, k, 120] = 1
    if iMA > 0.0:
        v[bi] = vA
        w[bi] = wA
    if bj >= 0:
        if iMB > 0.0:
            v[bj] = vB
            w[bj] = wB

@wp.kernel(module='unique')
def fixed_trace(porder: wp.array(dtype=int), pidx: wp.array(dtype=int), pstart: wp.array(dtype=int), pcount: wp.array(dtype=int), pbi: wp.array(dtype=int), pbj: wp.array(dtype=int), ci: int, cstart: wp.array(dtype=int), ccount: wp.array(dtype=int), cbi: wp.array(dtype=int), cbj: wp.array(dtype=int), cpA: wp.array(dtype=wp.vec3), cpB: wp.array(dtype=wp.vec3), cn: wp.array(dtype=wp.vec3), jn: wp.array(dtype=float), jt1: wp.array(dtype=float), jt2: wp.array(dtype=float), xc: wp.array(dtype=wp.vec3), v: wp.array(dtype=wp.vec3), w: wp.array(dtype=wp.vec3), invIw: wp.array(dtype=wp.mat33), invM: wp.array(dtype=float), mu: float, t2d: float, trace: wp.array3d(dtype=wp.float64), seen: wp.array3d(dtype=int)):
    """Sequential pair chunk with normal-derived tangent coordinates."""
    t = wp.tid()
    if t >= ccount[ci]:
        return
    p = porder[cstart[ci] + t]
    st = pstart[p]
    n = pcount[p]
    bi = pbi[p]
    bj = pbj[p]
    iMA = invM[bi]
    IA = invIw[bi]
    vA = v[bi]
    wA = w[bi]
    iMB = float(0.0)
    IB = invIw[bi]
    vB = wp.vec3(0.0, 0.0, 0.0)
    wB = wp.vec3(0.0, 0.0, 0.0)
    if bj >= 0:
        iMB = invM[bj]
        IB = invIw[bj]
        vB = v[bj]
        wB = w[bj]
    for k in range(n):
        c = pidx[st + k]
        nrm = cn[c]
        trace[t, k, 0] = wp.float64(nrm[0])
        seen[t, k, 0] = 1
        trace[t, k, 1] = wp.float64(nrm[1])
        seen[t, k, 1] = 1
        trace[t, k, 2] = wp.float64(nrm[2])
        seen[t, k, 2] = 1
        rA = cpA[c] - xc[bi]
        trace[t, k, 3] = wp.float64(rA[0])
        seen[t, k, 3] = 1
        trace[t, k, 4] = wp.float64(rA[1])
        seen[t, k, 4] = 1
        trace[t, k, 5] = wp.float64(rA[2])
        seen[t, k, 5] = 1
        va = vA + wp.cross(wA, rA)
        trace[t, k, 6] = wp.float64(va[0])
        seen[t, k, 6] = 1
        trace[t, k, 7] = wp.float64(va[1])
        seen[t, k, 7] = 1
        trace[t, k, 8] = wp.float64(va[2])
        seen[t, k, 8] = 1
        vb = wp.vec3(0.0, 0.0, 0.0)
        trace[t, k, 9] = wp.float64(vb[0])
        seen[t, k, 9] = 1
        trace[t, k, 10] = wp.float64(vb[1])
        seen[t, k, 10] = 1
        trace[t, k, 11] = wp.float64(vb[2])
        seen[t, k, 11] = 1
        rB = wp.vec3(0.0, 0.0, 0.0)
        trace[t, k, 12] = wp.float64(rB[0])
        seen[t, k, 12] = 1
        trace[t, k, 13] = wp.float64(rB[1])
        seen[t, k, 13] = 1
        trace[t, k, 14] = wp.float64(rB[2])
        seen[t, k, 14] = 1
        if bj >= 0:
            rB = cpB[c] - xc[bj]
            trace[t, k, 15] = wp.float64(rB[0])
            seen[t, k, 15] = 1
            trace[t, k, 16] = wp.float64(rB[1])
            seen[t, k, 16] = 1
            trace[t, k, 17] = wp.float64(rB[2])
            seen[t, k, 17] = 1
            vb = vB + wp.cross(wB, rB)
            trace[t, k, 18] = wp.float64(vb[0])
            seen[t, k, 18] = 1
            trace[t, k, 19] = wp.float64(vb[1])
            seen[t, k, 19] = 1
            trace[t, k, 20] = wp.float64(vb[2])
            seen[t, k, 20] = 1
        vrel = va - vb
        trace[t, k, 21] = wp.float64(vrel[0])
        seen[t, k, 21] = 1
        trace[t, k, 22] = wp.float64(vrel[1])
        seen[t, k, 22] = 1
        trace[t, k, 23] = wp.float64(vrel[2])
        seen[t, k, 23] = 1
        vn = wp.dot(vrel, nrm)
        trace[t, k, 24] = wp.float64(vn)
        seen[t, k, 24] = 1
        vt = vrel - vn * nrm
        trace[t, k, 25] = wp.float64(vt[0])
        seen[t, k, 25] = 1
        trace[t, k, 26] = wp.float64(vt[1])
        seen[t, k, 26] = 1
        trace[t, k, 27] = wp.float64(vt[2])
        seen[t, k, 27] = 1
        mt = wp.length(vt)
        trace[t, k, 28] = wp.float64(mt)
        seen[t, k, 28] = 1
        aa = wp.vec3(1.0, 0.0, 0.0)
        trace[t, k, 29] = wp.float64(aa[0])
        seen[t, k, 29] = 1
        trace[t, k, 30] = wp.float64(aa[1])
        seen[t, k, 30] = 1
        trace[t, k, 31] = wp.float64(aa[2])
        seen[t, k, 31] = 1
        if wp.abs(nrm[0]) >= 0.9:
            aa = wp.vec3(0.0, 1.0, 0.0)
            trace[t, k, 32] = wp.float64(aa[0])
            seen[t, k, 32] = 1
            trace[t, k, 33] = wp.float64(aa[1])
            seen[t, k, 33] = 1
            trace[t, k, 34] = wp.float64(aa[2])
            seen[t, k, 34] = 1
        t1 = wp.normalize(aa - wp.dot(aa, nrm) * nrm)
        trace[t, k, 35] = wp.float64(t1[0])
        seen[t, k, 35] = 1
        trace[t, k, 36] = wp.float64(t1[1])
        seen[t, k, 36] = 1
        trace[t, k, 37] = wp.float64(t1[2])
        seen[t, k, 37] = 1
        t2 = wp.cross(nrm, t1)
        trace[t, k, 38] = wp.float64(t2[0])
        seen[t, k, 38] = 1
        trace[t, k, 39] = wp.float64(t2[1])
        seen[t, k, 39] = 1
        trace[t, k, 40] = wp.float64(t2[2])
        seen[t, k, 40] = 1
        rnA = wp.cross(rA, nrm)
        trace[t, k, 41] = wp.float64(rnA[0])
        seen[t, k, 41] = 1
        trace[t, k, 42] = wp.float64(rnA[1])
        seen[t, k, 42] = 1
        trace[t, k, 43] = wp.float64(rnA[2])
        seen[t, k, 43] = 1
        meff = iMA + wp.dot(rnA, IA * rnA)
        trace[t, k, 44] = wp.float64(meff)
        seen[t, k, 44] = 1
        if bj >= 0:
            rnB = wp.cross(rB, nrm)
            trace[t, k, 45] = wp.float64(rnB[0])
            seen[t, k, 45] = 1
            trace[t, k, 46] = wp.float64(rnB[1])
            seen[t, k, 46] = 1
            trace[t, k, 47] = wp.float64(rnB[2])
            seen[t, k, 47] = 1
            meff = meff + iMB + wp.dot(rnB, IB * rnB)
            trace[t, k, 48] = wp.float64(meff)
            seen[t, k, 48] = 1
        if meff >= 1e-12:
            dj = -vn / meff
            trace[t, k, 49] = wp.float64(dj)
            seen[t, k, 49] = 1
            nw = wp.max(0.0, jn[c] + dj)
            trace[t, k, 50] = wp.float64(nw)
            seen[t, k, 50] = 1
            dj = nw - jn[c]
            trace[t, k, 51] = wp.float64(dj)
            seen[t, k, 51] = 1
            jn[c] = nw
            Jn = dj * nrm
            trace[t, k, 52] = wp.float64(Jn[0])
            seen[t, k, 52] = 1
            trace[t, k, 53] = wp.float64(Jn[1])
            seen[t, k, 53] = 1
            trace[t, k, 54] = wp.float64(Jn[2])
            seen[t, k, 54] = 1
            if iMA > 0.0:
                vA = vA + Jn * iMA
                trace[t, k, 55] = wp.float64(vA[0])
                seen[t, k, 55] = 1
                trace[t, k, 56] = wp.float64(vA[1])
                seen[t, k, 56] = 1
                trace[t, k, 57] = wp.float64(vA[2])
                seen[t, k, 57] = 1
                wA = wA + IA * wp.cross(rA, Jn)
                trace[t, k, 58] = wp.float64(wA[0])
                seen[t, k, 58] = 1
                trace[t, k, 59] = wp.float64(wA[1])
                seen[t, k, 59] = 1
                trace[t, k, 60] = wp.float64(wA[2])
                seen[t, k, 60] = 1
            if bj >= 0:
                if iMB > 0.0:
                    vB = vB - Jn * iMB
                    trace[t, k, 61] = wp.float64(vB[0])
                    seen[t, k, 61] = 1
                    trace[t, k, 62] = wp.float64(vB[1])
                    seen[t, k, 62] = 1
                    trace[t, k, 63] = wp.float64(vB[2])
                    seen[t, k, 63] = 1
                    wB = wB - IB * wp.cross(rB, Jn)
                    trace[t, k, 64] = wp.float64(wB[0])
                    seen[t, k, 64] = 1
                    trace[t, k, 65] = wp.float64(wB[1])
                    seen[t, k, 65] = 1
                    trace[t, k, 66] = wp.float64(wB[2])
                    seen[t, k, 66] = 1
            va = vA + wp.cross(wA, rA)
            trace[t, k, 67] = wp.float64(va[0])
            seen[t, k, 67] = 1
            trace[t, k, 68] = wp.float64(va[1])
            seen[t, k, 68] = 1
            trace[t, k, 69] = wp.float64(va[2])
            seen[t, k, 69] = 1
            vb = wp.vec3(0.0, 0.0, 0.0)
            trace[t, k, 70] = wp.float64(vb[0])
            seen[t, k, 70] = 1
            trace[t, k, 71] = wp.float64(vb[1])
            seen[t, k, 71] = 1
            trace[t, k, 72] = wp.float64(vb[2])
            seen[t, k, 72] = 1
            if bj >= 0:
                vb = vB + wp.cross(wB, rB)
                trace[t, k, 73] = wp.float64(vb[0])
                seen[t, k, 73] = 1
                trace[t, k, 74] = wp.float64(vb[1])
                seen[t, k, 74] = 1
                trace[t, k, 75] = wp.float64(vb[2])
                seen[t, k, 75] = 1
            vrel = va - vb
            trace[t, k, 76] = wp.float64(vrel[0])
            seen[t, k, 76] = 1
            trace[t, k, 77] = wp.float64(vrel[1])
            seen[t, k, 77] = 1
            trace[t, k, 78] = wp.float64(vrel[2])
            seen[t, k, 78] = 1
            rtA1 = wp.cross(rA, t1)
            trace[t, k, 79] = wp.float64(rtA1[0])
            seen[t, k, 79] = 1
            trace[t, k, 80] = wp.float64(rtA1[1])
            seen[t, k, 80] = 1
            trace[t, k, 81] = wp.float64(rtA1[2])
            seen[t, k, 81] = 1
            meft1 = iMA + wp.dot(rtA1, IA * rtA1)
            trace[t, k, 82] = wp.float64(meft1)
            seen[t, k, 82] = 1
            rtA2 = wp.cross(rA, t2)
            trace[t, k, 83] = wp.float64(rtA2[0])
            seen[t, k, 83] = 1
            trace[t, k, 84] = wp.float64(rtA2[1])
            seen[t, k, 84] = 1
            trace[t, k, 85] = wp.float64(rtA2[2])
            seen[t, k, 85] = 1
            meft2 = iMA + wp.dot(rtA2, IA * rtA2)
            trace[t, k, 86] = wp.float64(meft2)
            seen[t, k, 86] = 1
            if bj >= 0:
                rtB1 = wp.cross(rB, t1)
                trace[t, k, 87] = wp.float64(rtB1[0])
                seen[t, k, 87] = 1
                trace[t, k, 88] = wp.float64(rtB1[1])
                seen[t, k, 88] = 1
                trace[t, k, 89] = wp.float64(rtB1[2])
                seen[t, k, 89] = 1
                meft1 = meft1 + iMB + wp.dot(rtB1, IB * rtB1)
                trace[t, k, 90] = wp.float64(meft1)
                seen[t, k, 90] = 1
                rtB2 = wp.cross(rB, t2)
                trace[t, k, 91] = wp.float64(rtB2[0])
                seen[t, k, 91] = 1
                trace[t, k, 92] = wp.float64(rtB2[1])
                seen[t, k, 92] = 1
                trace[t, k, 93] = wp.float64(rtB2[2])
                seen[t, k, 93] = 1
                meft2 = meft2 + iMB + wp.dot(rtB2, IB * rtB2)
                trace[t, k, 94] = wp.float64(meft2)
                seen[t, k, 94] = 1
            if meft1 >= 1e-12:
                if meft2 >= 1e-12:
                    o1 = jt1[c]
                    trace[t, k, 95] = wp.float64(o1)
                    seen[t, k, 95] = 1
                    o2 = jt2[c]
                    trace[t, k, 96] = wp.float64(o2)
                    seen[t, k, 96] = 1
                    a1 = o1 - wp.dot(vrel, t1) / meft1
                    trace[t, k, 97] = wp.float64(a1)
                    seen[t, k, 97] = 1
                    a2 = o2 - wp.dot(vrel, t2) / meft2
                    trace[t, k, 98] = wp.float64(a2)
                    seen[t, k, 98] = 1
                    mag = wp.sqrt(a1 * a1 + a2 * a2)
                    trace[t, k, 99] = wp.float64(mag)
                    seen[t, k, 99] = 1
                    lim = mu * jn[c]
                    trace[t, k, 100] = wp.float64(lim)
                    seen[t, k, 100] = 1
                    if mag > lim and mag > 1e-12:
                        a1 = a1 * lim / mag
                        trace[t, k, 101] = wp.float64(a1)
                        seen[t, k, 101] = 1
                        a2 = a2 * lim / mag
                        trace[t, k, 102] = wp.float64(a2)
                        seen[t, k, 102] = 1
                    jt1[c] = a1
                    jt2[c] = a2
                    Jt = (a1 - o1) * t1 + t2d * (a2 - o2) * t2
                    trace[t, k, 103] = wp.float64(Jt[0])
                    seen[t, k, 103] = 1
                    trace[t, k, 104] = wp.float64(Jt[1])
                    seen[t, k, 104] = 1
                    trace[t, k, 105] = wp.float64(Jt[2])
                    seen[t, k, 105] = 1
                    if iMA > 0.0:
                        vA = vA + Jt * iMA
                        trace[t, k, 106] = wp.float64(vA[0])
                        seen[t, k, 106] = 1
                        trace[t, k, 107] = wp.float64(vA[1])
                        seen[t, k, 107] = 1
                        trace[t, k, 108] = wp.float64(vA[2])
                        seen[t, k, 108] = 1
                        wA = wA + IA * wp.cross(rA, Jt)
                        trace[t, k, 109] = wp.float64(wA[0])
                        seen[t, k, 109] = 1
                        trace[t, k, 110] = wp.float64(wA[1])
                        seen[t, k, 110] = 1
                        trace[t, k, 111] = wp.float64(wA[2])
                        seen[t, k, 111] = 1
                    if bj >= 0:
                        if iMB > 0.0:
                            vB = vB - Jt * iMB
                            trace[t, k, 112] = wp.float64(vB[0])
                            seen[t, k, 112] = 1
                            trace[t, k, 113] = wp.float64(vB[1])
                            seen[t, k, 113] = 1
                            trace[t, k, 114] = wp.float64(vB[2])
                            seen[t, k, 114] = 1
                            wB = wB - IB * wp.cross(rB, Jt)
                            trace[t, k, 115] = wp.float64(wB[0])
                            seen[t, k, 115] = 1
                            trace[t, k, 116] = wp.float64(wB[1])
                            seen[t, k, 116] = 1
                            trace[t, k, 117] = wp.float64(wB[2])
                            seen[t, k, 117] = 1
    if iMA > 0.0:
        v[bi] = vA
        w[bi] = wA
    if bj >= 0:
        if iMB > 0.0:
            v[bj] = vB
            w[bj] = wB
